

services:
  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - user-services
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES=[{"id":"user-services","uri":"lb://user-services","predicates":[{"path":"/users/**"}]}]
    networks:
      - app-network

  # User Service
  user-services:
    build:
      context: ./user-services
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka/
    networks:
      - app-network

  # Frontend Service
  # frontend:
  #   build:
  #     context: ../graduation-front  # Relative path to the frontend directory
  #   ports:
  #     - "5173:5173"  # Expose Vite default port
  #   networks:
  #     - app-network
  #   environment:
  #     - VITE_API_URL=http://api-gateway:8084  # Example environment variable, you may adjust this
  #   depends_on:
  #     - api-gateway
  #   command: ["npm", "run", "preview"]  # Start the Vite preview server in production mode
  #   volumes:
  #     - ../graduation-front:/app  # Mount the front-end directory to the container for live code changes (optional)

networks:
  app-network:
    driver: bridge